apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/matthew-beckett/multipaper-server
    newTag: feature-dockerfile
  - name: ghcr.io/matthew-beckett/multipaper-master
    newTag: feature-dockerfile

resources:
  - ./multipaper-master-deployment.yaml
  - ./multipaper-master-service.yaml