apiVersion: apps/v1
kind: Deployment
metadata:
  name: multipaper-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: multipaper-server
  template:
    metadata:
      labels:
        app: multipaper-server
    spec:
      containers:
        - name: multipaper-server
          image: ghcr.io/matthew-beckett/multipaper-server
          env:
            - name: MULTIPAPER_MASTER_ADDRESS
              value: "127.0.0.1:25585"
          resources:
            limits:
              memory: 1.5G
              cpu: 500m
            requests:
              cpu: 250m
              memory: 1G