apiVersion: apps/v1
kind: Deployment
metadata:
  name: multipaper-master
  namespace: multipaper 
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: multipaper-master
  template:
    metadata:
      labels:
        app: multipaper-master
    spec:
      containers:
        - name: multipaper-master
          image: ghcr.io/matthew-beckett/multipaper-master
          env:
            - name: MULTIPAPER_MASTER_PORT
              value: "25585"
          resources:
            limits:
              memory: 1G
              cpu: 500m
            requests:
              cpu: 100m
              memory: 250m
          ports:
            - name: multipaper
              containerPort: 25585
              protocol: TCP
            - name: proxy
              containerPort: 25565
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 25585
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: 25585
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10